name: dsh
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scikit-image
  - pillow
  - matplotlib
  - seaborn
  - line_profiler
  - memory_profiler
  - numexpr
  - pandas-datareader
  - netcdf4
  - ipympl